### ISSUE TITLE
Compatability with Quick Advanced Editor Plus

### ISSUE THREAD

**Issue by aolko** [martec/myinsertcommand#1]
subj
anyway, what templates should i modify?

**Comment by martec** [comment]
if you using mybb 1.8.6 not need made anything.

**Comment by aolko** [comment]
well, then why it won't display the insert button in the quick editor?

**Comment by martec** [comment]
so give me test admin account your forum in https://martec.ml/test/index.php

user: test
pass: test123

need register, but not need activation.

create thread inside of folder Support of Miuna Shoutbox

i will close here, i will continue give support in Support of Miuna Shoutbox folder in https://martec.ml/test/index.php
